---
apiVersion: v1
kind: Service
metadata:
  name: authentication
spec:
  selector:
    app: authentication
  ports:
    - protocol: TCP
      port: 3000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: authentication
spec:
  replicas: 1
  selector:
    matchLabels:
      app: authentication
  template:
    metadata:
      labels:
        app: authentication
    spec:
      containers:
        - name: authentication
          image: authentication:latest
          ports:
            - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: enter-data
spec:
  selector:
    app: enter-data
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: enter-data
spec:
  replicas: 1
  selector:
    matchLabels:
      app: enter-data
  template:
    metadata:
      labels:
        app: enter-data
    spec:
      containers:
        - name: enter-data
          image: enter-data:latest
          ports:
            - containerPort: 5000
          env:
            - name: MYSQL_HOST
              value: mysql-db
            - name: MYSQL_PASSWORD
              value: SeCur3Pas5w0rd
            - name: AUTH_URL
              value: http://authentication:3000
---
apiVersion: v1
kind: Service
metadata:
  name: mysql-db
spec:
  selector:
    app: mysql-db
  ports:
    - protocol: TCP
      port: 3306
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql-db
  template:
    metadata:
      labels:
        app: mysql-db
    spec:
      containers:
        - name: mysql-db
          image: mysql:latest
          env:
            - name: MYSQL_DATABASE
              value: data-db
            - name: MYSQL_ROOT_PASSWORD
              value: SeCur3Pas5w0rd
          ports:
            - containerPort: 3306
---
apiVersion: v1
kind: Service
metadata:
  name: mongo
spec:
  selector:
    app: mongo
  ports:
    - protocol: TCP
      port: 27017
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongo
  template:
    metadata:
      labels:
        app: mongo
    spec:
      containers:
        - name: mongo
          image: mongo:latest
          ports:
            - containerPort: 27017
          env:
            - name: MONGO_INITDB_ROOT_USERNAME
              value: user
            - name: MONGO_INITDB_ROOT_PASSWORD
              value: Secur3PAssw0rd
---
apiVersion: v1
kind: Service
metadata:
  name: show-results
spec:
  selector:
    app: show-results
  ports:
    - protocol: TCP
      port: 5004
      targetPort: 5004
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: show-results
spec:
  replicas: 1
  selector:
    matchLabels:
      app: show-results
  template:
    metadata:
      labels:
        app: show-results
    spec:
      containers:
        - name: show-results
          image: show-results:latest
          ports:
            - containerPort: 5004
          env:
            - name: MONGO_HOST
              value: mongo
            - name: MONGO_PORT
              value: "27017"
            - name: MONGO_PASSWORD
              value: Secur3PAssw0rd
            - name: MONGO_USERNAME
              value: user
            - name: AUTH_URL
              value: http://authentication:3000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: analytics
spec:
  replicas: 1
  selector:
    matchLabels:
      app: analytics
  template:
    metadata:
      labels:
        app: analytics
    spec:
      containers:
        - name: analytics
          image: analytics-service:latest
          env:
            - name: MYSQL_HOST
              value: mysql-db
            - name: MYSQL_PASSWORD
              value: SeCur3Pas5w0rd
            - name: MONGO_HOST
              value: mongo
            - name: MONGO_PORT
              value: "27017"
            - name: MONGO_USERNAME
              value: user
            - name: MONGO_PASSWORD
              value: Secur3PAssw0rd
---
apiVersion: v1
kind: Service
metadata:
  name: analytics
spec:
  selector:
    app: analytics
  ports:
    - protocol: TCP
      port: 80
