apiVersion: v1
kind: Service
metadata:
  name: authentication
spec:
  selector:
    app: authentication
  ports:
    - protocol: TCP
      port: 3000
  type: LoadBalancer  # Change from ClusterIP to LoadBalancer
---
apiVersion: v1
kind: Service
metadata:
  name: enter-data
spec:
  selector:
    app: enter-data
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
  type: LoadBalancer  # Change from ClusterIP to LoadBalancer
---
apiVersion: v1
kind: Service
metadata:
  name: mysql-db
spec:
  selector:
    app: mysql-db
  ports:
    - protocol: TCP
      port: 3306
  type: LoadBalancer  # Change from ClusterIP to LoadBalancer
---
apiVersion: v1
kind: Service
metadata:
  name: mongo
spec:
  selector:
    app: mongo
  ports:
    - protocol: TCP
      port: 27017
  type: LoadBalancer  # Change from ClusterIP to LoadBalancer
---
apiVersion: v1
kind: Service
metadata:
  name: show-results
spec:
  selector:
    app: show-results
  ports:
    - protocol: TCP
      port: 5004
      targetPort: 5004
  type: LoadBalancer  # Change from ClusterIP to LoadBalancer
---
apiVersion: v1
kind: Service
metadata:
  name: analytics
spec:
  selector:
    app: analytics
  ports:
    - protocol: TCP
      port: 80
  type: LoadBalancer  # Change from ClusterIP to LoadBalancer
