apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: show-results-hpa
spec:
  scaleTargetRef:
    apiVersion: v1
    kind: Service
    name: show-results
  minReplicas: 2  # Minimum number of replicas
  maxReplicas: 5  # Maximum number of replicas
  targetCPUUtilizationPercentage: 1

---

apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: enter-data-hpa
spec:
  scaleTargetRef:
    apiVersion: v1
    kind: Deployment 
    name: enter-data
  minReplicas: 2  # Minimum number of replicas
  maxReplicas: 5  # Maximum number of replicas
  targetCPUUtilizationPercentage: 1
---

apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: authentication-hpa
spec:
  scaleTargetRef:
    apiVersion: v1
    kind: Deployment  
    name: authentication
  minReplicas: 2  # Minimum number of replicas
  maxReplicas: 5  # Maximum number of replicas
  targetCPUUtilizationPercentage: 1
---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: analytics-hpa
spec:
  scaleTargetRef:
    apiVersion: v1
    kind: Deployment  
    name: analytics
  minReplicas: 2  # Minimum number of replicas
  maxReplicas: 5  # Maximum number of replicas
  targetCPUUtilizationPercentage: 1

---

apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: mongo-hpa
spec:
  scaleTargetRef:
    apiVersion: v1
    kind: Deployment 
    name: mongo
  minReplicas: 2  # Minimum number of replicas
  maxReplicas: 5  # Maximum number of replicas
  targetCPUUtilizationPercentage: 1

---

apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: mysql-db-hpa
spec:
  scaleTargetRef:
    apiVersion: v1
    kind: Deployment  
    name: mysql-db
  minReplicas: 2  # Minimum number of replicas
  maxReplicas: 5  # Maximum number of replicas
  targetCPUUtilizationPercentage: 1




